version: '3.1'
services:
  api:
    build: .
    ports:
    - "80:8080"
    environment:
    - SECRETS_BUCKET_NAME=dev-leveledup-api-config
    image:  365769272576.dkr.ecr.us-west-2.amazonaws.com/leveledup-api:dev-latest