version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.7.5

    working_directory: /go/src/github.com/strongjz/leveledup-api/
    steps:
      - checkout
      - setup_remote_docker   # (2)
      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      - run:
          name: Install Docker client
          command: |
                  set -x
                  VER="17.06.0-ce"
                  curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
                  tar -xz -C /tmp -f /tmp/docker-$VER.tgz
                  mv /tmp/docker/* /usr/bin

      - run: |
          go get -u github.com/kardianos/govendor
          govendor init
          govendor get
          docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG .
      - run: docker run -d -p 8080:8080 --name $IMAGE_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG ; sleep 10
      - run: curl --retry 10 --retry-delay 5 localhost:8080/health | grep "Connected to Database"
      - run: .circleci/deploy_dev.sh
      - deploy:
          command: .circleci/deploy_dev.sh
          name: Deploy Image to ECR



