version: 2
jobs:
  build:
    machine: true
    working_directory: $GOPATH/src/github.com/strongjz/leveledup-api/
    steps:
      - checkout
      - run:
          command: |
            make deploy



