version: 2
jobs:
  build:
    machine: true
    working_directory: $GOPATH/src/github.com/strongjz/leveledup-api/
    steps:
      - checkout
      - run:
          working_directory: $GOPATH/src/github.com/strongjz/leveledup-api
          command: ls -la
      - run:
          working_directory: $GOPATH/src/github.com/strongjz/leveledup-api
          command: cat Makefile
      - run:
          working_directory: $GOPATH/src/github.com/strongjz/leveledup-api
          command: make deploy