version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          working_directory: $GOPATH/src/github.com/strongjz/leveledup-api/
          command: make deploy
          


