version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.7.5
    working_directory: /go/src/github.com/strongjz/leveledup.api
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
          version: 17.06.0-ce
      - run:
          name: Dependencies
          command: apk add --no-cache make git curl openssh      
      - run:
          working_directory: /go/src/github.com/strongjz/leveledup.api
          command: make deploy