version: 2
jobs:
  build:
    machine: true
    working_directory: /go/src/github.com/strongjz/leveledup-api/
    steps:
      - checkout
      - deploy:
          command: make deploy
          name: Deploy Image to ECR



