version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.7.5
    working_directory: /go/src/github.com/strongjz/leveledup.api
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
          version: 17.06.0-ce
      - run:
          command: |
            curl -O https://bootstrap.pypa.io/get-pip.py
            python get-pip.py --user
            ~/.local/bin/pip install awscli --upgrade --user
      - run:
          working_directory: /go/src/github.com/strongjz/leveledup.api
          command: make deploy