version: 2
jobs:
  build:
    working_directory: $GOPATH/src/github.com/strongjz/leveledup-api
    docker:
      - image: docker:17.06.0-ce
    steps:
      - setup_remote_docker:
          reusable: true
          exclusive: true
          version: 17.06.0-ce
      - run:
          name: Dependencies
          command: apk add --no-cache make git curl openssh
      - checkout
      - run:
          working_directory: $GOPATH/src/github.com/strongjz/leveledup-api
          command: make deploy